name: Copyright check

on: workflow_call

jobs:
  copyright-check:
    name: Copyright check
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install copyright-check
        run: pip install https://github.com/eclipse-kura/copyright-check/releases/download/0.1.0/copyright_check-0.1.0-py3-none-any.whl

      - name: Run check
        run: copyright-check -c .github/copyright-config.yml $(git diff --name-only HEAD^1 HEAD)
