name: Copyright check

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  copyright-check:
    name: Copyright check
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: '3.13'

      - name: Install copyright-check
        run: pip install https://github.com/eclipse-kura/copyright-check/releases/download/0.2.0/copyright_check-0.2.0-py3-none-any.whl

      - name: Run check
        run: copyright-check -d -c ${{ inputs.config-path }} $(git diff --name-only HEAD^1 HEAD)
